### ISSUE TITLE
Query Apps is broken

### ISSUE THREAD

**Issue by dynamitemedia** [zankich/groku#3]
Example:

groku apps
2015/02/25 16:17:34 XML syntax error on line 33: unexpected EOF

same issue if you try launch app Example:
groku app "Netflix"
2015/02/25 16:19:18 XML syntax error on line 33: unexpected EOF

.

**Comment by zankich** [comment]
@dynamitemedia sorry for the delay, github didn't notify me of this issue!

Did you build from source? If so, which version of go are you running and on what operating system?

**Comment by zankich** [comment]
@dynamitemedia This has been fixed in the 0.4 release
